#!/bin/bash
#BSUB -P CSC276
#BSUB -W 2:00
#BSUB -nnodes 256 
#BSUB -J hyper256 
#BSUB -o outhyper256.%J
#BSUB -e errhyper256.%J

export PATH="/gpfs/alpinetds/proj-shared/csc276/yngtodd/anaconda3/bin:$PATH"

#BSEC Module
BSECMODULEDIR=/gpfs/alpinetds/csc276/proj-shared/modules
[[ -d $BSECMODULEDIR/modulefiles ]] && module use $BSECMODULEDIR/modulefiles

module load pytorch 

cd /gpfs/alpinetds/proj-shared/csc276/yngtodd/ringingbells/mtcnn/twofiftysix

date
jsrun -n 256 -a 1 -g 6 python hyperdrive.py --results_dir /gpfs/alpinetds/proj-shared/csc276/yngtodd/ringingbells/mtcnn/twofiftysix/results 
