#!/bin/bash
#BSUB -P CSC276
#BSUB -W 2:00
#BSUB -nnodes 64 
#BSUB -J hyper64 
#BSUB -o outhyper64.%J
#BSUB -e errhyper64.%J

export PATH="/gpfs/alpinetds/proj-shared/csc276/yngtodd/anaconda3/bin:$PATH"

#BSEC Module
BSECMODULEDIR=/gpfs/alpinetds/csc276/proj-shared/modules
[[ -d $BSECMODULEDIR/modulefiles ]] && module use $BSECMODULEDIR/modulefiles

module load pytorch 

cd /gpfs/alpinetds/proj-shared/csc276/yngtodd/ringingbells/mtcnn/sixtyfour

date
jsrun -n 64 -a 1 -g 6 python hyperdrive.py --results_dir /gpfs/alpinetds/proj-shared/csc276/yngtodd/ringingbells/mtcnn/sixtyfour/results 
